cotf_contracts/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from cotf_contracts import settings
from services.download import download

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('download/<contract_number>', download, name='download')
]

main/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.views.static import serve

from cotf_contracts import settings
from main import views
from services.download import download
urlpatterns = [
    path('', views.ContractTemplateListAndCreateView.as_view(), name='contract_template_list'),
    path('contracts/', views.ContractListView.as_view(), name='contract_list'),
    path('agreement/<contract_number>/', views.FillingQuestionnaireView.as_view(), name='contract_detail'),
    path('administration/', views.AdministrationView.as_view(), name='administration')
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),

main/models.py
import time

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from babel.dates import format_date


cities = [
    ('Москва', 'Москва'),
    ('Санкт-Петербург', 'Санкт-Петербург')
]


def check_format_of_file(value):
    """Проверка формата на docx"""

    if not value.name.endswith('.docx'):
        raise ValidationError(u'Выберите файл с форматом .docx')


def check_format_of_payment(value):
    """Проверка формата на xlsx"""

    if not value.name.endswith('.xlsx'):
        raise ValidationError(u'Выберите файл с форматом .xlsx')


def check_format_signed_contract(value):
    """Проверка формата на pdf"""

    if not value.name.endswith('.pdf'):
        raise ValidationError(u'Выберите файл с форматом .pdf')


def _generator_num_contract():
    """Генератор номера договора"""

    try:
        contract = Contract.objects.last()
        contract_num = getattr(contract, 'number')
        return contract_num
    except AttributeError:
        return 24546799


class ContractTemplate(models.Model):
    """Модель для Шаблонов контркта"""

    class Statuses(models.TextChoices):
        """Модель выборы Статуса"""

        actual = 'Актуально', 'Актуально'
        outdated = 'Устарело', 'Устарело'

    class Types(models.TextChoices):
        """Модель выборы Типов"""

        basic = 'Основной', 'Основной'
        renewal = 'Продление', 'Продление'

    class Companies(models.TextChoices):
        """Модель выборы Компании"""

        CMS = 'ООО "КМС"', ('ООО "КМС"')
        DC = 'ООО "ДЕЛОВОЙ КЛУБ"', ('ООО "ДЕЛОВОЙ КЛУБ"')

    city = models.CharField('Город', choices=cities, null=True, max_length=50, default='Москва')

    name = models.CharField('Название', null=False, max_length=50, blank=True)
    template_of_contract = models.FileField('Шаблон договора', null=False, upload_to='upload/', validators=[check_format_of_file])
    amount = models.PositiveIntegerField('Сумма', null=True, default=None)
    status = models.CharField('Статус', choices=Statuses.choices, default=Statuses.actual, max_length=100)
    type = models.CharField('Тип', choices=Types.choices, null=False, max_length=50, default='Основной')
    # branch = models.ForeignKey('Branch', on_delete=models.CASCADE, blank=True)
    company = models.CharField('Компания', choices=Companies.choices, null=False, max_length=50)

    class Meta:
        verbose_name = 'Шаблон контракта'
        verbose_name_plural = 'Шаблоны контрактов'

    def save(self, *args, **kwargs):
        """Переопределение метода save для имени и слага"""

        self.name = str(self.type + ' ' + self.company)
        super(ContractTemplate, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Contract(models.Model):
    """Модель для Контркта"""

    class Statuses(models.TextChoices):
        """Модель выборы Статуса"""

        directed = 'Направлен', 'Направлен'
        signed = 'Подписан', 'Подписан'
        canceled = 'Отменен', 'Отменен'
        refusal = 'Отказ', 'Отказ'

    number = models.PositiveBigIntegerField('Номер договора', default=24546799, null=False)
    contract_template = models.ForeignKey(ContractTemplate, on_delete=models.CASCADE, null=False)
    payment = models.FileField('Счет на оплату', null=True, upload_to='payment/',
                               validators=[check_format_of_payment], blank=True)
    signed_contract = models.FileField('Подписанный договор', upload_to='signed_contract/',
                                       null=True)
    date_created = models.DateField('Дата генерации', default=timezone.now())
    date_signed = models.DateField('Дата подписания', blank=True, null=True)
    status = models.CharField('Статус', choices=Statuses.choices, default=Statuses.directed, max_length=50)
    full_name = models.CharField('ФИО', null=False, max_length=300)
    amount = models.PositiveIntegerField('Сумма', null=True,max_length=300)
    name = models.CharField('Название', max_length=400, null=False)
    series_passport = models.PositiveIntegerField('Серия паспорт', max_length=4, blank=True, null=True)
    num_passport = models.PositiveIntegerField('Номер паспорт', max_length=6, blank=True, null=True)
    email = models.EmailField('Почта', max_length=50, blank=True, null=True)
    phone = models.CharField('Телефон', max_length=20, blank=True, null=True)
    identifier = models.CharField('Индетификатор', max_length=50, blank=True, null=True, default='Данных нет')

    class Meta:
        verbose_name = 'Контракт'
        verbose_name_plural = 'Контракты'

    def save(self, *args, **kwargs):
        """Переопределение метода save для имени и номера договора"""

        self.name = str(self.contract_template.type + ' ' + self.full_name + ' ' +
                        self.contract_template.company + ' ' + format_date(self.date_created, 'd MMMM yyyy', locale='ru'))
        super(Contract, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('contract_detail', kwargs={'contract_number': str(self.number)})

    def __str__(self):
        return str(self.number)


class AuthenticationCode(models.Model):
    code = models.PositiveIntegerField('Код', null=False, unique=True, max_length=5)
    number_of_attempts = models.PositiveSmallIntegerField('Количество попыток ввода', default=0)
    date_generated_code = models.CharField('Секунды генерации кода', default=time.time(), max_length=1000)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, null=False)
    phone = models.CharField('Номер телефона', max_length=12)
    confirmation = models.BooleanField('Флаг подтверждения', default=False)
    relevance = models.BooleanField('Флаг актуальности')

    class Meta:
        verbose_name = 'Код аутентификации'
        verbose_name_plural = 'Коды аутентификации'

    def __str__(self):
        return str(self.code)

templates/administration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content">
    <a href="{% url 'contract_template_list' %}">Контракты</a>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta charset="UTF-8">
    <link class="css" href="{% static 'css/lib.css' %}" rel="stylesheet"/>
    <link class="css" href="{% static 'css/app.css' %}" rel="stylesheet"/>
    <title>Клуб Первых</title>
</head>
<body>
<div class="left-menu">
    <div class="logo">
        <img src="{% static 'logo.png' %}">
    </div>
    <ul class="menu">

        <li class="{% if request.path == '/events/' %}active{% endif %}">
            <a href="#">
                <i class="icon-events"></i>
                <span>Мероприятия</span>
            </a>
        </li>
        <li class="{% if request.path == '/messages/' %}active{% endif %}">
            <a href="#">
                <i class="icon-message"></i>
                <span>Сообщения</span>
            </a>
        </li>
        <li class="{% if request.path == '/forum/' %}active{% endif %}">
            <a href="#">
                <i class="icon-forum"></i>
                <span>Форумы</span>
            </a>
        </li>
        <li class="{% if request.path == '/projects/' %}active{% endif %}">
            <a href="#">
                <i class="icon-proekti"></i>
                <span>Проекты</span>
            </a>
        </li>
        <li class="{% if request.path == '/trips/' %}active{% endif %}">
            <a href="#">
                <i class="icon-map"></i>
                <span>Путешествия</span>
            </a>
        </li>
        <li class="{% if request.path == '/payment/' %}active{% endif %}">
            <a href="#">
                <i class="icon-oplata"></i>
                <span>Оплата</span>
            </a>
        </li>
        <li class="{% if request.path == '/tasks/' %}active{% endif %}">
            <a href="#">
                <i class="icon-zadachi"></i>
                <span>Задачи</span>
            </a>
        </li>
        <li class="{% if request.path == '/administration/' or request.path == '/' or request.path == '/contracts/' %}active{% endif %}">
            <a href="{% url 'administration' %}">
                <i class="icon-admin"></i>
                <span>Администрирование</span>
            </a>
        </li>
    </ul>
</div>

<div class="main-content">
    {% include 'common/navbar.html' %}
    {% block content %}
    {% endblock %}
</div>

<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
<script src="{% static 'js/app.js' %}"></script>
{% if show_modal %}
<script>
    document.getElementById('modal').click();
</script>
{% endif %}
</body>
</html>

templates/contract_creation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form action="" method="post" enctype="multipart/form-data">



                {% csrf_token %}
                {{ form.as_p }}

            <button type="submit">Отправить</button>

 </form>
<form method='POST'>
                    {% csrf_token %}

    <button type="submit" name="update" value="update">Проверить</button>
    </form>
</body>
</html>

templates/contract_templates_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="page-title">
            <a class="back" href="{% url 'administration' %}"><i class="icon-remove"></i></a>
            <h1>Договоры</h1>
        </div>
    </div>
    <div class="table-container container-fluid">
        {% include 'common/table_navbar.html' %}

        <div class="table-wrapper">
            <table class="table">
                <thead>
                <tr>
                    <td style="min-width: 200px;">
                        <div class="table_title">
                            Название
                            <div class="sort_controls">
                                <form action="." method="GET">
                                    <button class="up" name="name_max" value="name_max">
                                        <i class="icon-arrow_up"></i>
                                    </button>

                                    <button class="down" name="name_min" value="name_min">
                                        <i class="icon-arrow_down"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </td>
                    <td style="min-width: 150px;">
                        <div class="table_title">
                            Договор
                            <div class="sort_controls">
                                <form action="." method="GET">
                                    <button class="up" name="contract_max" value="contract_max">
                                        <i class="icon-arrow_up"></i>
                                    </button>
                                    <button class="down" name="contract_min" value="contract_min">
                                        <i class="icon-arrow_down"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </td>
                    <td style="min-width: 170px;">
                        <div class="table_title">
                            Статус
                            <div class="sort_controls">
                                <form action="." method="GET">
                                    <button class="up" name="status_max" value="status_max">
                                        <i class="icon-arrow_up"></i>
                                    </button>
                                    <button class="down" name="status_min" value="status_min">
                                        <i class="icon-arrow_down"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="table_title">
                            Идентификатор
                            <div class="sort_controls">
<!--                                <a class="up" href="#">-->
<!--                                    <i class="icon-arrow_up"></i>-->
<!--                                </a>-->
<!--                                <a class="down" href="#">-->
<!--                                    <i class="icon-arrow_down"></i>-->
<!--                                </a>-->
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="table_title">
                            Сумма
                            <div class="sort_controls">
                                <form action="." method="GET">
                                    <button class="up" name="status_max" value="status_max">
                                        <i class="icon-arrow_up"></i>
                                    </button>
                                    <button class="down" name="status_min" value="status_min">
                                        <i class="icon-arrow_down"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </td>
                    <td style="min-width: 50px;"></td>
                </tr>
                </thead>
                <tbody>


                {% for contract in contract_template_list %}
                <tr class="tr_contract">
                    <input name="contract_template_pk" type="hidden" value="{{ contract.pk }}">
                    <td>{{ contract.name }}</td>
                    <td class="light">Договор {{ contract.pk }}</td>
                    <td id="status">
                        <div class="dropdown status_box">
                            <input name="status" type="hidden" value="{% if contract.status == 'Актуально' %}Устарело{% else %}Актуально{% endif %}">
                            <button class="btn {% if contract.status == 'Актуально' %}btn_cyan{% else %}btn_gray{% endif %}">
                                {{ contract.status }}
                                <i class="icon-select"></i>
                            </button>
                            <div class="cancel">
                                {% if contract.status == 'Устарело' %}
                                    <img src="{% static 'icon/actual.svg' %}">
                                    <span>Сделать актуальным</span>
                                {% else %}
                                    <span>Устарело</span>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                    <td>
                        <input class="input input-id" name="identifier" value="{{ contract.full_name }}"
                               {% if contract.status == 'Устарело' %}disabled{% endif %}
                        >
                    </td>
                    <td>
                        <input class="input input-sum" name="amount" value="{{ contract.amount }}"
                               {% if contract.status == 'Устарело' %}disabled{% endif %}
                        >
                    </td>
                    <td>
                        <div class="url_copy_btn" data-status="{{ contract.status }}">
                            <img src="{% static 'icon/file.svg' %}">
                            <input name="contract_url" type="hidden" value="random_url">
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="alert_wrapper">
            <div class="alert alert-dismissible fade copy_success_alert" role="alert">
          Добавлена новая запись во вкладке Договоры.<br>
            Сформированная ссылка скопирована в буфер обмена.
          <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close">
              <img src="{% static 'icon/close.svg' %}">
          </button>
        </div>
        </div>

        <div class="d-flex justify-content-end">
            {% include 'common/pagination.html' with items=contract_template_list %}
        </div>
    </div>

    <div aria-hidden="true" class="modal fade" id="contract_add_modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <h2>Создать шаблон</h2>
                <form action="" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{ form_contract_template.create_form }}

                    <div class="form-group">
                        <label for="id_type">
                            {{ form_contract_template.type.label }}*
                        </label><br>
                        {{ form_contract_template.type }}
                        {{ form_contract_template.type.errors }}
                    </div>

                    <div class="form-group">
                        <label for="id_city">
                            {{ form_contract_template.city.label }}*
                        </label><br>
                        {{ form_contract_template.city }}
                        {{ form_contract_template.city.errors }}
                    </div>

                    <div class="form-group">
                        <label for="id_company">
                            {{ form_contract_template.company.label }}*
                        </label><br>
                        {{ form_contract_template.company }}
                        {{ form_contract_template.company.errors }}
                    </div>

                    <div class="form-group">
                        <label for="id_doc" class="label_file_name">
                            Договор*<br>
                            <input readonly class="input_file_name" name="id_doc">
                            <img src="{% static 'icon/upload.svg' %}">
                        </label>
                    </div>

                    <div class="form-group">
                        <label for="id_amount">
                            {{ form_contract_template.amount.label }}
                        </label><br>
                        {{ form_contract_template.amount }}
                        {{ form_contract_template.amount.errors }}
                    </div>

                    <div class="d-flex justify-content-between">
                        <label for="id_template_of_contract">+ Загрузить договор</label>
                    </div>

                    {{ form_contract_template.template_of_contract }}


                    {{ message }}
                    {% if valid %}
                        <div class="_alert alert-success">
                            <img src="{% static 'icon/success.svg' %}">
                            <div class="msg">Все переменные указаны верно</div>
                        </div>
                    {% endif %}
                    {% if template_errors %}
                        <div class="_alert alert-danger">
                                <img src="{% static 'icon/danger.svg' %}">
                                <div class="msg">
                                    <span>Отсутствуют или внесены неверно переменные:</span><br>
                                    <span>{{ form_contract_template.template_of_contract.errors }}</span><br>
                                    <span>Пожалуйста, загрузите исправленный документ и выполните проверку повторно</span>
                                </div>
                        </div>
                    {% endif %}
                    <div class="buttons">
                        <button class="btn" data-bs-dismiss="modal" type="button">Отмена</button>
                        {% if valid %}
                            <button class="btn btn_grd" name="save">Сохранить</button>
                        {% else %}
                            <button class="btn btn_grd" name="check_file">Проверить</button>
                        {% endif %}
                    </div>

                </form>
            </div>
        </div>
    </div>

    <form action="" id="contract_update_form" method="POST">
        <input name="csrfmiddlewaretoken" type="hidden" value="{{ csrf_token }}">
    </form>
</div>
<div class="copy_alert alert">Ссылка скопирована</div>
{% endblock %}

templates/contracts_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for contracts in contract_list %}

    <p>
        {{ contracts.name }}, {{ contracts.pk }}  <form action="" method="post" enctype="multipart/form-data">



    <input type="hidden" name="contract_template" value="{{ contracts.pk }}">
    {% if contracts.amount != 0 %}
        <input name="amount_bitch" value="{{ contracts.amount }}">
    {% else %}

    {% endif %}
                <form>{% csrf_token %}

                {{ form.as_p }}
            <button type="submit">Создать</button></form>
</form>
    </p>
{% endfor %}
<a href="contract-creation/">creat </a>
</body>
</html>